# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  ifc.edu.br:
    site_hosts:
      - canonical: website.fabricadesoftware.ifc.edu.br
        redirects:
          - www.website.fabricadesoftware.ifc.edu.br
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: ssh://git@git.fabricadesoftware.ifc.edu.br:1022/yurihs/ifc-dezessete.git
    branch: master
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    site_title: IFC
    admin_email: admin@ifc.test
    multisite:
      enabled: true
      subdomains: true
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: true
